language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
script: tox

notifications:
  email:
    on_failure: change
env:
    global:
      - TEST_PYPI_URL=https://test.pypi.org/legacy/
      - PYPI_URL=https://pypi.python.org/pypi
install:
  - pip install --upgrade pip && pip install -r dev-requirements.txt && pip install -r requirements.txt
cache: pip
stages:
  - test
  - local_installation_test
  - coverage
  - build_docs
  - integration_tests
  - deploy_to_pypi
  - pypi_installation_test
jobs:
  include:
    - stage: local_installation_test
      if: branch = master
      script: bash tests/local_installation_test.sh
    - stage: coverage
      python:
        - "3.4"
        - "3.5"
      script: coverage run --rcfile=.coveragerc setup.py test -s tests.unit
    - stage: build_docs
      script: cd sphinx && make clean && make html
    - stage: integration_tests
      script: cd tests/integration && tox
    - stage: deploy_to_pypi
      script: bash deploy/deploy_to_pypi.sh
    - stage: pypi_installation_test
      if: branch = master
      script: bash tests/pypi_installation_test.sh