language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
script: tox
after_success:
  - coveralls

notifications:
  email:
    on_failure: change
env:
    global:
      - TEST_PYPI_URL=https://test.pypi.org/legacy/
      - PYPI_URL=https://pypi.python.org/pypi
      -
install:
  - pip install --upgrade pip && pip install -r dev-requirements.txt && pip install .
cache: pip

stages:
  - test
  - "Local Installation Test"
  - "Build docs"
  - "Deploy to PyPI"
  - "PyPI Installation Test"

jobs:
  include:
    - &local_installation_test
      stage: "Local Installation Test"
      python: 3.4
      script: bash tests/local_installation_test.sh
    - <<: *local_installation_test
      python: 3.5
    - <<: *local_installation_test
      python: 3.6
    - <<: *local_installation_test
      python: "3.7-dev"

    - stage: "Build docs"
      script: cd sphinx && make clean && make html

    - &deploy_to_pypi
      stage: "Deploy to PyPI"
      python: 3.4
      script: bash deploy/deploy_to_pypi.sh
    - <<: *deploy_to_pypi
      python: 3.5
    - <<: *deploy_to_pypi
      python: 3.6
    - <<: *deploy_to_pypi
      python: "3.7-dev"

    - &pypi_installation_test
      stage: "PyPI Installation Test"
      python: 3.4
      if: branch = master
      script: bash tests/pypi_installation_test.sh
    - <<: *pypi_installation_test
      python: 3.5
    - <<: *pypi_installation_test
      python: 3.6
    - <<: *pypi_installation_test
      python: "3.7-dev"