language: python
notifications:
  email:
    on_failure: change
install:
  - pip install --upgrade pip
  - pip install coverage tox-travis virtualenv coveralls
stages:
  - unit_tests
  - local_installation_test
  - coverage
jobs:
  include:
    - stage: unit_tests
      dist: xenial
      sudo: false
      python:
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7-dev"
      script: tox
    - stage: local_installation_test
      dist: xenial
      sudo: false
      python:
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7-dev"
      script: bash tests/local_installation_test.sh
    - stage: coverage
      dist: xenial
      sudo: false
      python:
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7-dev"
      script: coverage run --rcfile=.coveragerc setup.py test -s tests.unit
deploy:
  - provider: pypi   # test PyPI
    distributions: "sdist bdist_egg bdist_wheel"
    skip_existing: true
    user: csparpa
    server: https://test.pypi.org/legacy/ # Remove to deploy to real PyPI
    password:
      secure: "DhttNLUg1XLIu+qHCoiat9DN5VGgC3fH5/FQpXnW2cw32eIcwng4DTUA4pQYcnlDO1fBXSG/ysgSsz7QnxqML5UZKwPobAUis4TkKPFRQbJumKEpFOSkRjQYi2uF2pEtJwflr+BUAYd9lo7L9uhV9CyYb99DZq5R++K+slHmxeM="
    on:
      branch: develop
      repo: csparpa/pyowm








