language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install coveralls==0.4.2 tox==1.9.2
script:
  - tox
  - coverage run --rcfile=.coveragerc setup.py test -s tests.unit
after_success:
  coveralls
notifications:
  email:
    on_failure: change
