language: python
dist: xenial
sudo: false
notifications:
  email:
    on_failure: change
env:
    global:
      - TEST_PYPI_URL=https://test.pypi.org/legacy/
      - PYPI_URL=https://pypi.python.org/pypi
install:
  - pip install --upgrade pip
  - pip install coverage tox-travis virtualenv coveralls twine
script: tox
stages:
  - unit_tests
  - local_installation_test
  - coverage
  - deploy_to_pypi
  - pypi_installation_test
jobs:

  include:
    - stage: unit_tests
      script: bash tests/run_unit_tests.sh
      python:
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7-dev"
    - stage: local_installation_test
      script: bash tests/local_installation_test.sh
    - stage: coverage
      script: coverage run --rcfile=.coveragerc setup.py test -s tests.unit
    - stage: deploy_to_pypi
      script: bash deploy/deploy_to_pypi.sh
    - stage: pypi_installation_test
      script: bash tests/pypi_installation_test.sh