language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install --upgrade pip
  - pip install coverage tox-travis virtualenv coveralls
jobs:
  include:
    - stage: unit tests
      script:
        - tox
        - coverage run --rcfile=.coveragerc setup.py test -s tests.unit
        - bash tests/local_installation_test.sh
    - stage: deploy to testpypi
      deploy:
        provider: pypi
        distributions: "sdist bdist_egg bdist_wheel"
        user: csparpa
        server: https://test.pypi.org/legacy # Remove to deploy to real PyPI
        password:
          secure: "iedpYQh2nQVy9qGg0Qx/l1eSjhoWgFc5g6GQX7rERPcco8ylAFdnyaGylWA9LsrDk4rjwkuKb7JLn3LjuBQ8KY8c4dZ3dBpsXGwTbPQ20MSBU9wWVBSk+U9/b8mQBFPoSJJh2Y6GaNwPOJjO9AhfrNdFOd1pJjO+ohwPs3ZTNy0="
        on:
          branch: develop
          repo: csparpa/test-pyowm
stages:
  - test
  - deploy
after_success:
  coveralls
notifications:
  email:
    on_failure: change
dist: xenial
sudo: false









